### ISSUE TITLE
大佬的项目苹果审核过了吗？

### ISSUE THREAD

**Issue by chqike** [yukuyoulei/ILRuntime_HotGames#10]
看readme里还没更新结果，感觉有点慌，动手前想先问问：）

**Comment by yukuyoulei** [comment]
哈哈，不好意思，审核过了，我们只是把登录界面和主界面两个界面放到里面就审核过了。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: chqike <notifications@github.com>
发送时间: Thursday, May 16, 2019 10:53:52 AM
收件人: yukuyoulei/ILRuntime_HotGames
抄送: Subscribed
主题: [yukuyoulei/ILRuntime_HotGames] 大佬的项目苹果审核过了吗？ (#10)


看readme里还没更新结果，感觉有点慌，动手前想先问问：）

―

**Comment by yukuyoulei** [comment]
稍候会将释放资源这部分功能加到框架里。
