### ISSUE TITLE
AHotGames中dll的更新.

### ISSUE THREAD

**Issue by mar-sir** [yukuyoulei/ILRuntime_HotGames#12]
假设AHotGames这个项目依赖一个dll名叫A.dll,那么怎么处理A.dll的更新？

**Comment by yukuyoulei** [comment]
以newtonsoft.json.dll举例，热更项目中正常依赖它（右键点击，add reference / 找到newtonsoft.json.dll），如果想更新它，直接在文件夹里替换它就行了。

如果你是想问怎么热更这个a.dll，那只能很遗憾的告诉你，暂时不可以，如果这个dll真的非常需要热更，你只能把它的源码放到热更项目中。

**Comment by mar-sir** [comment]
是的，我就是想热更a.dll，a.dll里面有好多消息体，打包运行的后是找不到a.dll里面的类的

**Comment by yukuyoulei** [comment]
我觉得你遇到的是代码剥离方面的问题，link.xml里面有没有配置这个dll？
建议你把a.dll的源码直接放到热更项目中好了。
