### ISSUE TITLE
ahotgames工程打开报错

### ISSUE THREAD

**Issue by ismakegame** [yukuyoulei/ILRuntime_HotGames#16]
unity 2019 vs2017 frame 4.6.1 打开报错。提示UnityEngine.dll中找不到Input 如果更新引用unity安装目录的UnityEngine.dll 那么引起UnityEngine和core的冲突。。。
--

**Comment by yukuyoulei** [comment]
这个报错参考ILRuntime官方文档，需要打开一下主项目，确保主项目工程的dll已经生成（Unity在生成主项目dll的同时也会复制它所依赖的UnityEngine.dll等到相应目录，AHotGames项目依赖的是这些dll），不需要手动修改AHotGames的依赖

**Comment by ismakegame** [comment]
还是没成功  unity 2019 4.5。 步骤： 打开unity 运行main。相关dll 生成在UHotGames\Library\ScriptAssemblies但文件夹中没找到unityengine.dll（因为用的vscode。所以没有用vs打开u项目。所以也没f6）。打开AHotGames 发现 Newtonsoft.Json和unity相关 引用异常。引用路径为空。

**Comment by yukuyoulei** [comment]
了解了，是因为Unity2019开始将UnityEngine拆分成了数个小dll，自行加一下依赖就好了。

近期我会将最新的框架上传到github，最新框架修改了热更项目的引用方式，从主项目外编译修改成了使用asmdef来管理，可以一劳永逸的解决这种依赖冲突，敬请期待。
