### ISSUE TITLE
请问提示这玩意可咋整呀

### ISSUE THREAD

**Issue by sbllf** [yukuyoulei/ILRuntime_HotGames#18]
MissingMethodException: Default constructor not found for type AEntrance

**Comment by sbllf** [comment]
我的unity版本是2018.4.36f1

**Comment by yukuyoulei** [comment]
确认一下Unity的脚本版本是不是4.x

**Comment by sbllf** [comment]
Api Compatibility Level*是.NET 4.x

**Comment by yukuyoulei** [comment]
你是不是没有自己编译然后调用自己的dll，而是调用的我这边旧的dll呀？我这边gitpage里的旧的dll好久没有更新过了- _ - !!!
