### ISSUE TITLE
unity Macro define error

### ISSUE THREAD

**Issue by maxwellDoge** [yukuyoulei/ILRuntime_HotGames#19]
when opening at 2019 or newer Unity will Compile Error. 
![image](https://user-images.githubusercontent.com/32019183/137706877-c6f6f4d9-e054-4c65-8ff5-1313266ceb97.png)

change to 
![image](https://user-images.githubusercontent.com/32019183/137706934-4f16cf7c-7724-42d9-b238-cdf57a1449f6.png)

**Comment by yukuyoulei** [comment]
fixed
