### ISSUE TITLE
提议：Config.txt 应该支持自动更新等

### ISSUE THREAD

**Issue by KervenGame** [yukuyoulei/ILRuntime_HotGames#4]
Config.txt 不会自动更新？需要手动更新。
提议：1.在打包的时候更新Config.txt；2.Config.txt和Windows等资源目录统一放在ab1下；3.加一个支持配置了服务器相关权限后可上传的功能？如开启了ftp,打包时配置好路径可直接更新服务器资源，不需要开发再拷贝复制到服务器上。
我写一下，写完了提个pr给你。

**Comment by yukuyoulei** [comment]
首先十分感谢您的热心支持。


关于Config.txt：
如果您留意了的话，其实UseAB这个变量只在编辑器模式下才会启用，
Enter.cs 
line 65
#if UNITY_EDITOR
        UConfigManager.bUsingAb = UseAB;
#endif


也就是说，Release出来的版本中关于是否加载AB是会读取Config.txt中的配置的。


其次，Config.txt这个配置表中的每一行配置其实都是支持多版本控制的，
ConfigDownloader.cs
line 80
    public string OnGetValue(string skey)
    {
        if (dKeyValue.ContainsKey(skey + Utils_Plugins.Util_GetBundleVersion()))
        {
            return dKeyValue[skey + Utils_Plugins.Util_GetBundleVersion()];
        }
        if (dKeyValue.ContainsKey(skey))
        {
            return dKeyValue[skey];
        }
        return "";
    }


在我们的公司项目中，Config.txt这个配置文件其实是扔在一个配置很低的小水管云服务器上的，它现在已经有上百行了，而且它不走cdn，因为它的内容很重要，每次加载它都会加时间戳以保证它最新，而所有的AB文件都是集中放在一个大硬盘并且走cdn的，所以它并不适合和ab放在一起。


关于 ftp：
开启ftp是一个好主意，不过我们是用的svn来进行版本管理，而且设置了提交前hook，必须要填写注释才允许提交。这两种方式都可以，你可以酌情使用。






在 2019-01-05 15:59:13，"kerven" <notifications@github.com> 写道：


Config.txt 不会自动更新？需要手动更新。
提议：1.在打包的时候更新Config.txt；2.Config.txt和Windows等资源目录统一放在ab1下；3.加一个支持配置了服务器相关权限后可上传的功能？如开启了ftp,打包时配置好路径可直接更新服务器资源，不需要开发再拷贝复制到服务器上。
我写一下，写完了提个pr给你。

**Comment by yukuyoulei** [comment]
没有别的问题就close掉了，有问题再reopen吧。
