### ISSUE TITLE
把Canvas作为预设的一部分的做法不太合理

### ISSUE THREAD

**Issue by KervenGame** [yukuyoulei/ILRuntime_HotGames#5]
例子中的预设：UILogin等，把Canvas作为预设的一部分的做法不太合理，在unity2018.2.16f1中，把父节点为把Canvas的预设重新拖放到场景中会出现“Assertion failed on expression: 'modifications.empty()'
UnityEditorInternal.InternalEditorUtility:HierarchyWindowDrag()
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)”的错误，这个错误不影响运行。不过个人建议是在场景中应含一个Canvas，加载任何预设都应挂到这个Canvas下。

**Comment by yukuyoulei** [comment]
这就属于个人习惯问题了 ^__^

至于那个报错，其实我个人已经习惯了新版Unity的各种莫名其妙的报错提示了，只要不是代码问题，已经习惯性无视它了。

场景中含一个Canvas将预设加载到这个Canvas下是一个好主意，不过我个人一直倾向于一个预设就是一个完整的功能的制作理念，这样测试起来会很方便，而且某些UI可能会和其他UI的设定不太一样，比如渲染深度，比如拉伸等，当然，这些都是可以在开发过程中逐渐流程化，标准化的，说到底还是一个习惯问题。

以上~
