### ISSUE TITLE
开发中该怎么调试AHotGames

### ISSUE THREAD

**Issue by chqike** [yukuyoulei/ILRuntime_HotGames#9]
开发中该怎么调试AHotGames

**Comment by yukuyoulei** [comment]
ILRuntime的原文档里有怎么调试。

https://ourpalm.github.io/ILRuntime/public/v1/guide/tutorial.html

不过我简单尝试了一下，没有成功，之后就没再试了，现在有问题我都是看堆栈或者打log。
